In [1]:
## D-Tale Library EDA Outomation Tool
!pip install dtale

Collecting dtale
  Downloading dtale-2.15.2-py2.py3-none-any.whl (14.0 MB)
     ---------------------------------------- 14.0/14.0 MB 6.7 MB/s eta 0:00:00
Collecting dash-colorscales
  Downloading dash_colorscales-0.0.4.tar.gz (62 kB)
     -------------------------------------- 62.3/62.3 kB 416.9 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting missingno<=0.4.2
  Downloading missingno-0.4.2-py3-none-any.whl (9.7 kB)
Collecting dash-bootstrap-components<=1.3.1
  Downloading dash_bootstrap_components-1.3.1-py3-none-any.whl (219 kB)
     -------------------------------------- 219.7/219.7 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: itsdangerous in e:\anaconda3\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: matplotlib<=3.6.0 in e:\anaconda3\lib\site-packages (from dtale) (3.5.2)
Requirement already satisfied: xarray in e:\anaconda3\lib\site-packages (from dtale) (0.20.1)
Requirement already satisfied: certifi in e:\anaconda3\lib\site-packages (from dtale) (2022.9.14)
Collecting Flask-Compress
  Downloading Flask_Compress-1.13-py3-none-any.whl (7.9 kB)
Requirement already satisfied: cycler in e:\anaconda3\lib\site-packages (from dtale) (0.11.0)
Requirement already satisfied: lz4 in e:\anaconda3\lib\site-packages (from dtale) (3.1.3)
Requirement already satisfied: numpy in e:\anaconda3\lib\site-packages (from dtale) (1.21.5)
Requirement already satisfied: plotly in e:\anaconda3\lib\site-packages (from dtale) (5.9.0)
Requirement already satisfied: statsmodels in e:\anaconda3\lib\site-packages (from dtale) (0.13.2)
Requirement already satisfied: scipy<=1.9.3 in e:\anaconda3\lib\site-packages (from dtale) (1.9.1)
Requirement already satisfied: openpyxl!=3.2.0b1 in e:\anaconda3\lib\site-packages (from dtale) (3.0.10)
Requirement already satisfied: et-xmlfile in e:\anaconda3\lib\site-packages (from dtale) (1.1.0)
Collecting flask-ngrok
  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Requirement already satisfied: requests in e:\anaconda3\lib\site-packages (from dtale) (2.28.1)
Collecting dash-daq
  Downloading dash_daq-0.5.0.tar.gz (642 kB)
     -------------------------------------- 642.7/642.7 kB 6.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: xlrd in e:\anaconda3\lib\site-packages (from dtale) (2.0.1)
Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-win_amd64.whl (65.9 MB)
     ---------------------------------------- 65.9/65.9 MB 2.5 MB/s eta 0:00:00
Collecting squarify
  Downloading squarify-0.4.3-py3-none-any.whl (4.3 kB)
Requirement already satisfied: future>=0.14.0 in e:\anaconda3\lib\site-packages (from dtale) (0.18.2)
Requirement already satisfied: beautifulsoup4 in e:\anaconda3\lib\site-packages (from dtale) (4.11.1)
Collecting strsimpy
  Downloading strsimpy-0.2.1-py3-none-any.whl (45 kB)
     --------------------------------------- 45.9/45.9 kB 95.0 kB/s eta 0:00:00
Requirement already satisfied: six in e:\anaconda3\lib\site-packages (from dtale) (1.16.0)
Requirement already satisfied: seaborn in e:\anaconda3\lib\site-packages (from dtale) (0.11.2)
Collecting dash
  Downloading dash-2.9.3-py3-none-any.whl (10.2 MB)
     ---------------------------------------- 10.2/10.2 MB 7.0 MB/s eta 0:00:00
Requirement already satisfied: scikit-learn in e:\anaconda3\lib\site-packages (from dtale) (1.0.2)
Requirement already satisfied: networkx in e:\anaconda3\lib\site-packages (from dtale) (2.8.4)
Requirement already satisfied: pandas in e:\anaconda3\lib\site-packages (from dtale) (1.4.4)
Requirement already satisfied: Flask in e:\anaconda3\lib\site-packages (from dtale) (1.1.2)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Requirement already satisfied: Werkzeug>=0.15 in e:\anaconda3\lib\site-packages (from Flask->dtale) (2.0.3)
Requirement already satisfied: click>=5.1 in e:\anaconda3\lib\site-packages (from Flask->dtale) (8.0.4)
Requirement already satisfied: Jinja2>=2.10.1 in e:\anaconda3\lib\site-packages (from Flask->dtale) (2.11.3)
Requirement already satisfied: kiwisolver>=1.0.1 in e:\anaconda3\lib\site-packages (from matplotlib<=3.6.0->dtale) (1.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in e:\anaconda3\lib\site-packages (from matplotlib<=3.6.0->dtale) (3.0.9)
Requirement already satisfied: fonttools>=4.22.0 in e:\anaconda3\lib\site-packages (from matplotlib<=3.6.0->dtale) (4.25.0)
Requirement already satisfied: packaging>=20.0 in e:\anaconda3\lib\site-packages (from matplotlib<=3.6.0->dtale) (21.3)
Requirement already satisfied: pillow>=6.2.0 in e:\anaconda3\lib\site-packages (from matplotlib<=3.6.0->dtale) (9.2.0)
Requirement already satisfied: python-dateutil>=2.7 in e:\anaconda3\lib\site-packages (from matplotlib<=3.6.0->dtale) (2.8.2)
Requirement already satisfied: tenacity>=6.2.0 in e:\anaconda3\lib\site-packages (from plotly->dtale) (8.0.1)
Requirement already satisfied: soupsieve>1.2 in e:\anaconda3\lib\site-packages (from beautifulsoup4->dtale) (2.3.1)
Collecting brotli
  Downloading Brotli-1.0.9-cp39-cp39-win_amd64.whl (383 kB)
     -------------------------------------- 383.4/383.4 kB 2.4 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2020.1 in e:\anaconda3\lib\site-packages (from pandas->dtale) (2022.1)
Requirement already satisfied: charset-normalizer<3,>=2 in e:\anaconda3\lib\site-packages (from requests->dtale) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in e:\anaconda3\lib\site-packages (from requests->dtale) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in e:\anaconda3\lib\site-packages (from requests->dtale) (3.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in e:\anaconda3\lib\site-packages (from scikit-learn->dtale) (2.2.0)
Requirement already satisfied: joblib>=0.11 in e:\anaconda3\lib\site-packages (from scikit-learn->dtale) (1.1.0)
Requirement already satisfied: patsy>=0.5.2 in e:\anaconda3\lib\site-packages (from statsmodels->dtale) (0.5.2)
Requirement already satisfied: colorama in e:\anaconda3\lib\site-packages (from click>=5.1->Flask->dtale) (0.4.5)
Requirement already satisfied: MarkupSafe>=0.23 in e:\anaconda3\lib\site-packages (from Jinja2>=2.10.1->Flask->dtale) (2.0.1)
Building wheels for collected packages: dash-colorscales, dash-daq
  Building wheel for dash-colorscales (setup.py): started
  Building wheel for dash-colorscales (setup.py): finished with status 'done'
  Created wheel for dash-colorscales: filename=dash_colorscales-0.0.4-py3-none-any.whl size=62566 sha256=f3d81124d4b3c4bf78659fab606a74fc3a99d18f05eb37bac44315b12a33d72d
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\ec\32\ec\dc8a1aa820182edf280a5e26c76fc9493ae29e196735708de2
  Building wheel for dash-daq (setup.py): started
  Building wheel for dash-daq (setup.py): finished with status 'done'
  Created wheel for dash-daq: filename=dash_daq-0.5.0-py3-none-any.whl size=669692 sha256=a9d5171383af3e5b287b21919bc25cf51356e84757bc181222389dc9459d1396
  Stored in directory: c:\users\hp\appdata\local\pip\cache\wheels\53\73\ea\8a422aab5cab848d88653ed3087c1fa05553c3fbd67fb6ab75
Successfully built dash-colorscales dash-daq
Installing collected packages: strsimpy, squarify, kaleido, dash-table, dash-html-components, dash-core-components, dash-colorscales, brotli, flask-ngrok, Flask-Compress, dash, missingno, dash-daq, dash-bootstrap-components, dtale
Successfully installed Flask-Compress-1.13 brotli-1.0.9 dash-2.9.3 dash-bootstrap-components-1.3.1 dash-colorscales-0.0.4 dash-core-components-2.0.0 dash-daq-0.5.0 dash-html-components-2.0.0 dash-table-5.0.0 dtale-2.15.2 flask-ngrok-0.0.25 kaleido-0.2.1 missingno-0.4.2 squarify-0.4.3 strsimpy-0.2.1

In [15]:
import seaborn as sns
import pandas as pd
import dtale
df=sns.load_dataset('titanic')
#df1=sns.load_dataset('hr_cleaned.csv')

ValueError: 'hr_cleaned.csv' is not one of the example datasets.

In [9]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
#import dtale
dtale.show(df)
df.drop(columns=['embarked', 'class', 'deck', 'embark_town'], inplace=True)

E:\anaconda3\lib\site-packages\dtale\views.py:756: FutureWarning:

['embarked', 'class', 'deck', 'embark_town'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.